<?php

namespace Database\Seeders;

use App\Models\IncomingTransaction;
use App\Models\IncomingTransactionItem;
use App\Models\OutgoingTransaction;
use App\Models\OutgoingTransactionItem;
use App\Models\Product;
use App\Models\Supplier;
use App\Models\User;
use Carbon\Carbon;
use Faker\Factory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = User::first(); // Menggunakan user pertama (Admin) sebagai creator
        $suppliers = Supplier::all();
        $products = Product::all();

        if ($user === null || $suppliers->isEmpty() || $products->isEmpty()) {
            $this->command?->warn('Seeding dibatalkan: data user, supplier, atau product kosong. Jalankan DatabaseSeeder terlebih dahulu.');

            return;
        }

        // Reset stok produk ke 0 dulu agar perhitungan akurat dari awal (Opsional)
        // Product::query()->update(['current_stock' => 0]);

        $this->command?->info('Seeding incoming transactions (barang masuk)...');
        $this->seedIncomingTransactions($user, $suppliers, $products);

        $this->command?->info('Seeding outgoing transactions (barang keluar)...');
        $this->seedOutgoingTransactions($user, $products);

        $this->command?->info('Transaction seeding completed.');
    }

    private function seedIncomingTransactions(User $user, Collection $suppliers, Collection $products): void
    {
        $statuses = [
            IncomingTransaction::STATUS_PENDING,
            IncomingTransaction::STATUS_VERIFIED,
            IncomingTransaction::STATUS_COMPLETED,
            IncomingTransaction::STATUS_REJECTED,
        ];

        for ($i = 1; $i <= 20; $i++) {
            $status = $statuses[array_rand($statuses)];
            $date = Carbon::now()->subDays(rand(0, 30));

            // Generate Transaction Number manual untuk seeder (PO-YYYYMMDD-XXXX)
            $trxNumber = 'PO-'.$date->format('Ymd').'-'.str_pad($i, 4, '0', STR_PAD_LEFT);

            $transaction = IncomingTransaction::create([
                'transaction_number' => $trxNumber,
                'transaction_date' => $date,
                'supplier_id' => $suppliers->random()->id,
                'created_by' => $user->id,
                'verified_by' => in_array($status, [IncomingTransaction::STATUS_VERIFIED, IncomingTransaction::STATUS_COMPLETED], true)
                    ? $user->id
                    : null,
                'status' => $status,
                'notes' => 'Auto-generated by seeder',
                'total_items' => 0,
                'total_quantity' => 0,
                'total_amount' => 0,
            ]);

            // Create Items
            $totalItems = 0;
            $totalQty = 0;
            $totalAmount = 0;

            // Ambil produk acak
            $productSampleSize = max(1, min($products->count(), rand(1, 5)));
            $randomProducts = $products->random($productSampleSize);

            foreach ($randomProducts as $product) {
                $qty = rand(10, 100);
                $cost = $product->purchase_price;
                $lineTotal = $qty * $cost;

                IncomingTransactionItem::create([
                    'incoming_transaction_id' => $transaction->id,
                    'product_id' => $product->id,
                    'quantity' => $qty,
                    'unit_cost' => $cost,
                    'line_total' => $lineTotal,
                ]);

                $totalItems++;
                $totalQty += $qty;
                $totalAmount += $lineTotal;

                // Update Stock jika status verified/completed
                if (in_array($status, [IncomingTransaction::STATUS_VERIFIED, IncomingTransaction::STATUS_COMPLETED], true)) {
                    $product->increment('current_stock', $qty);
                }
            }

            // Update Header Totals
            $transaction->update([
                'total_items' => $totalItems,
                'total_quantity' => $totalQty,
                'total_amount' => $totalAmount,
            ]);
        }
    }

    private function seedOutgoingTransactions(User $user, Collection $products): void
    {
        $statuses = [
            OutgoingTransaction::STATUS_PENDING,
            OutgoingTransaction::STATUS_APPROVED,
            OutgoingTransaction::STATUS_SHIPPED,
        ];

        $faker = Factory::create('id_ID');

        for ($i = 1; $i <= 20; $i++) {
            $status = $statuses[array_rand($statuses)];
            $date = Carbon::now()->subDays(rand(0, 30));

            // Generate Transaction Number (SO-YYYYMMDD-XXXX)
            $trxNumber = 'SO-'.$date->format('Ymd').'-'.str_pad($i, 4, '0', STR_PAD_LEFT);

            $transaction = OutgoingTransaction::create([
                'transaction_number' => $trxNumber,
                'transaction_date' => $date,
                'customer_name' => $faker->name,
                'created_by' => $user->id,
                'approved_by' => in_array($status, [OutgoingTransaction::STATUS_APPROVED, OutgoingTransaction::STATUS_SHIPPED], true)
                    ? $user->id
                    : null,
                'status' => $status,
                'notes' => 'Auto-generated shipment',
                'total_items' => 0,
                'total_quantity' => 0,
                'total_amount' => 0,
            ]);

            // Create Items
            $totalItems = 0;
            $totalQty = 0;
            $totalAmount = 0;

            // Ambil produk acak
            $productSampleSize = max(1, min($products->count(), rand(1, 3)));
            $randomProducts = $products->random($productSampleSize);

            foreach ($randomProducts as $product) {
                // Pastikan stok cukup untuk dikurangi, ambil random kecil
                $currentStock = $product->fresh()->current_stock;
                $qty = rand(1, 5);

                // Jika stok 0, skip produk ini agar tidak error minus
                if ($currentStock < $qty && in_array($status, [OutgoingTransaction::STATUS_APPROVED, OutgoingTransaction::STATUS_SHIPPED], true)) {
                    continue;
                }

                $price = $product->sale_price;
                $lineTotal = $qty * $price;

                OutgoingTransactionItem::create([
                    'outgoing_transaction_id' => $transaction->id,
                    'product_id' => $product->id,
                    'quantity' => $qty,
                    'unit_price' => $price,
                    'line_total' => $lineTotal,
                ]);

                $totalItems++;
                $totalQty += $qty;
                $totalAmount += $lineTotal;

                // Update Stock jika status approved/shipped
                if (in_array($status, [OutgoingTransaction::STATUS_APPROVED, OutgoingTransaction::STATUS_SHIPPED], true)) {
                    $product->decrement('current_stock', $qty);
                }
            }

            // Update Header Totals
            $transaction->update([
                'total_items' => $totalItems,
                'total_quantity' => $totalQty,
                'total_amount' => $totalAmount,
            ]);
        }
    }
}
